language: python
python:
  - "3.4"
# install: "pip install -r Boggle_pt_2/LessonCode/requirements.txt"
script:
- 01-getting-started/test_boggle.py
- 01.c1-testing-larger-grids/test_boggle.py
- 02-optimising/test_boggle.py