language: python
python:
  - "3.4"
install: "pip install -r Boggle_pt_2/LessonCode/requirements.txt"
script:
- Boggle_pt_1/LessonCode/boggle.py
- Boggle_pt_1/LessonCode/test_boggle.py
- Boggle_pt_1/Challenge/boggle.py
- Boggle_pt_1/Challenge/test_boggle.py
- Boggle_pt_2/LessonCode/boggle.py
- Boggle_pt_2/LessonCode/test_boggle.py